# Generated by Django 3.0 on 2019-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='USD', max_length=20),
            preserve_default=False,
        ),
    ]
